Validations
mutinhiri/blog pull request #8
Opened 2022-03-04 10:19 UTC by mutinhiri

In this Pr i added validations for models 
Write unit tests for models
Secure app from n+1 problems

2022-03-04 11:36 UTC, DeliceLydia requested changes
## Hi @mutinhiri, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! Here are major highlights are:
- Kudos on writing tests
- No linter errors
- Followed git workflow


## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-03-04 11:36 UTC, DeliceLydia commented on app/views/users/index.html.erb
> +  <button class="button">New Post</button>
- [ ] When I try to create a post am getting an error you are missing `layouts/alert` partial
![post](https://user-images.githubusercontent.com/44745855/156752584-50f3e334-f735-4426-9872-56b92da7cd8f.png)

2022-03-04 11:36 UTC, DeliceLydia commented on app/views/users/index.html.erb
> +  <button class="button">New Post</button>
- [ ] Remember to check if your flash messages are working on `posts#create`, `comments#create`, and `likes#create`

2022-03-04 11:36 UTC, DeliceLydia commented on app/controllers/posts_controller.rb
>        end
- [ ] When i try to see all posts am getting an error
![fog](https://user-images.githubusercontent.com/44745855/156755150-3da5cca4-e0d8-4706-8309-3acdd1a2a237.png)

2022-03-04 11:36 UTC, DeliceLydia commented on app/controllers/posts_controller.rb
>        end
- [ ] This is happening as well when I try to see a post by ID `http://localhost:3000/users/1/posts/6` I am getting the same error

2022-03-04 16:19 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Bunbee,
### Great work on making the changes requested by a previous reviewer 👏 
### You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-04 16:19 UTC, SajjadAhmad14 commented on app/controllers/posts_controller.rb
>        end
I get the same error as pointed out by the previous code reviewer but it occurs when a user clicks on a post after he tries to add a comment on a post.
![post-show](https://user-images.githubusercontent.com/35504149/156799564-6f4032ba-6ae3-4f1d-b527-233cc84e6650.png)

2022-03-04 16:19 UTC, SajjadAhmad14 commented on app/controllers/comments_controller.rb
I get an error when I try to add a comment on a post. Kindly fix the error.
![comment](https://user-images.githubusercontent.com/35504149/156799892-6c212ce6-6dfa-4359-97c8-95e82461050b.png)

2022-03-05 15:37 UTC, mutinhiri commented
Dear code reviewer my system crashed yesterday and i am still in the middle of setting up my new environment. I could not test the app after making changes so i'd appreciate it if there are errors in this code we schedule a call and offer me some help. This is the last trial i have sent

2022-03-05 15:41 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Bunbee, 

Your project is complete! Great job for making the necessary changes recommended in the previous review. There is nothing else to say other than... it's time to merge it 🍾 :shipit:. Congratulations! 🎉🥂

<br>
Cheers and Happy coding!👏 💻 🍷 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-05 15:52 UTC, mutinhiri commented
Thank you @rloterh

2022-03-05 16:37 UTC, merged